### ISSUE TITLE
Null drawable

### ISSUE THREAD

**Issue by cesards** [cesards/CropImageView#14]
add a condition in order to avoid null pointers whenever we don't have an image set.

``` java
final Drawable image = getDrawable();
if (cropType != CropType.NONE && viewHeight > 0 && viewWidth > 0 && image != null) {
      final Matrix matrix = imageMaths.getMatrix();

      final int drawableWidth = image.getIntrinsicWidth();
      final int drawableHeight = image.getIntrinsicHeight();
```

**Comment by ViksaaSkool** [comment]
why don't you push the changes...

**Comment by cesards** [comment]
Sorry, I've been travelling and moving to another country. I will. Probably next weekend I'll retake everything from Github again! Sorry for that!

**Comment by cesards** [comment]
I have actually implemented that change ;-)

**Comment by ViksaaSkool** [comment]
Thanks.

**Comment by QiXi** [comment]
all as before. Please add changes. this awful bug

**Comment by cesards** [comment]
I'll push pending changes over the week @ViksaaSkool @QiXi :+1: (and new features as well :-P)

**Comment by Maragues** [comment]
@cesards is this library no longer maintained? If that's the case, please specify in the readme. There are some really useful PRs that have been sitting there for months.

Anyway, thanks for your time

**Comment by cesards** [comment]
Sorry guys. I'm into many things at the same time. I said 3 months ago in a few weeks I would push the changes... lol. Time goes so fast. I was working in the version 2.0, so it is being maintained, but  I haven't got much time for what I wanted to achieve! This has been fixed long ago, but it looks like it wasn't merged :-/
