### ISSUE TITLE
Crash if no drawable specified

### ISSUE THREAD

**Issue by chriswiesner** [cesards/CropImageView#17]
at com.cesards.cropimageview.CropImageView.computeImageMatrix(CropImageView.java:119)

causes crash if src is not specified in xml. So using an Image loading library does not work.
would suggest to add a null-check for the drawable

**Comment by MBratkowski** [comment]
+1

**Comment by jczerski** [comment]
+1

**Comment by yagi2** [comment]
+1

**Comment by cesards** [comment]
I owe you two beers each.I'll upload the new version to bintray next week

**Comment by david-serrano** [comment]
@cesards could the issue referenced here https://github.com/cesards/CropImageView/issues/26 be a regression on this past issue?

**Comment by cesards** [comment]
Fixed in the next version.

**Comment by cesards** [comment]
BTW, sorry about this:

> I owe you two beers each.I'll upload the new version to bintray next week

We all know LATER = NEVER

It was an easy fix but I left the library in a limbo of maintance :-(

Back to work on al the issues. Let me know if in any case you are getting errors after the new release.
