### ISSUE TITLE
App crashes upon adding CropImageView dependency in build.gradle

### ISSUE THREAD

**Issue by gamebusterz** [cesards/CropImageView#20]
Adding the dependency `compile 'com.cesards.android:cropimageview:1.0.2.1'` to **build.gradle(Module: app)** causes [RuntimeException](https://gist.github.com/gamebusterz/5023a86109e07439be61c9b723460f40). The App works fine on removing the dependency. Adding it again causes the app to crash as soon as it launches.
I tried reproducing it three times and it occurred all the three times.

**Comment by cesards** [comment]
I'm not sure the problem is related to the library.

Check this out:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

Anyway, I'm uploading a new version and I'll update the documentation. Hope the problem is fixed!
