### ISSUE TITLE
doesn't crop in xml

### ISSUE THREAD

**Issue by stavkidron** [cesards/CropImageView#22]
I tried using the library in xml according to the example and the image does not get cropped, it just shows the full image. I want the image to be cropped at the bottom. I tried any of the options, without any affect. How do I make it work in xml?

**Comment by cesards** [comment]
Could you provide more information? Screenshot? Phone? your XML?

**Comment by stavkidron** [comment]
Sorry, this is my code:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <com.cesards.cropimageview.CropImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/portrait"
        custom:civ_crop="topLeft" />

</LinearLayout>
```
my image:
[https://upload.wikimedia.org/wikipedia/commons/b/b6/17th-century_unknown_painters_-_Portrait_of_a_Silversmith_in_His_Workshop_(detail)_-_WGA23541.jpg](url)

it looks like this no matter what I write in the civ_crop:
![image](https://cloud.githubusercontent.com/assets/20288188/21962383/6985aba6-db2d-11e6-99cb-c8b8deb9edee.png)

**Comment by cesards** [comment]
Are you using an emulator? A phone? what brind and OS? I need to upload a new version of the library and I want to fix any pending issue :-)

**Comment by stavkidron** [comment]
I'm using the android studio emulator, with android 6.0 (API level 23).

**Comment by smarques84** [comment]
@cesards I do have the same problem as reported by @stavkidron android a nexus 5X running Android 7.0

`Error:(53) No resource identifier found for attribute 'civ_crop' in package 'com.***'`

**Comment by mirandole** [comment]
I have the same issue

**Comment by FernandoWahl** [comment]
I found the problem, the correct name of the attribute is 'crop'. Not 'civ_crop' as in example!

**Comment by FernandoWahl** [comment]
https://github.com/cesards/CropImageView/pull/21

**Comment by cesards** [comment]
@stavkidron 

I'm having a look to this again. I know what's going on. You are using:

```
android:layout_width="wrap_content"
android:layout_height="wrap_content"
```

in the image, so that means that if the image is smaller than the parent/screen, it's not going to crop. You should be using `match_parent` for that to happen. I'm going to close this. Let me know if you keep having problems 👍
