### ISSUE TITLE
Can't use with Picasso

### ISSUE THREAD

**Issue by manenga** [cesards/CropImageView#23]
I use Picasso to load my images but I need to use this library to correctly center my images but because this library extends FrameLayout and its imageView is private, I'm not able to use it. Any ways around this?

**Comment by cesards** [comment]
I'll have a look. Let's see what can I do about it :-)

**Comment by cesards** [comment]
The library doesn't extend FrameLayout. This should be working in the next release. Let me know if you have any more problems :)
