### ISSUE TITLE
NullPointerException on computeImageMatrix()

### ISSUE THREAD

**Issue by Bakhrom** [cesards/CropImageView#6]
NullPointerException in line:  int drawableWidth = getDrawable().getIntrinsicWidth();  if image not set

**Comment by cesards** [comment]
:+1: It will be solved in the next release :-) Easy check. I'm gonna go for tests ASAP. Thanks

**Comment by cesards** [comment]
This is already solved in https://github.com/cesards/CropImageView/commit/f44272a65a2d801b896bd182aafd5216538b37f2

I haven't uploaded version 1.0.2 to bintray. I'm going to go directly for the version 1.0.3 ;-)
